version: '3.9'

services:
  culture_aggregator:
    build:
      context: .
      args:
        ENV: development
    ports:
      - "8002:8000"
    volumes:
      - .:/app
    container_name: culture_aggregator
    env_file:
      - .env
    environment:
      - PICCOLO_CONF=piccolo_conf
    depends_on:
      - postgres
    networks:
      - culture_aggregator_network
    command: uvicorn main_server:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres:17.5
    container_name: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - culture_aggregator_network

networks:
  culture_aggregator_network:
    driver: bridge

volumes:
  postgres_data: