services:
  culture_aggregator:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: production
    container_name: culture_aggregator
    ports:
      - "8002:8000"
    env_file:
      - .env
    environment:
      - PICCOLO_CONF=piccolo_conf
    depends_on:
      postgres_data_culture:
        condition: service_healthy
    networks:
      - charity_aggregator_network
    command: uvicorn main_server:app --host 0.0.0.0 --port 8002

  postgres_data_culture:
    image: postgres:17.5
    container_name: postgres
    env_file:
      - .env
    ports:
      - '5434:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 3s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data_culture:/var/lib/postgresql/data
    networks:
      - charity_aggregator_network


networks:
  charity_aggregator_network:
    external: true

volumes:
  postgres_data_culture:
