worker_processes auto;

events {
    worker_connections 10240;
    use epoll;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;

    keepalive_timeout 65;
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # SSL config
    ssl_protocols TLSv1.3 TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    ssl_stapling on;
    ssl_stapling_verify on;
    resolver 8.8.8.8 8.8.4.4 valid=300s;
    resolver_timeout 5s;

    # HTTP/3 (QUIC) support
    ssl_early_data on;
    add_header Alt-Svc 'h3=":443"';  # HTTP/3 advertise

    server {
        listen 80;
        listen [::]:80;
        server_name travelculturehub.com www.travelculturehub.com;

        location /.well-known/acme-challenge/ {
            root /usr/share/nginx/html;
            try_files $uri =404;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl http2 reuseport;
        listen 443 quic reuseport;  # HTTP/3

        server_name travelculturehub.com www.travelculturehub.com;

        ssl_certificate /etc/letsencrypt/live/travelculturehub.com-0001/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/travelculturehub.com-0001/privkey.pem;
        ssl_trusted_certificate /etc/letsencrypt/live/travelculturehub.com-0001/chain.pem;


        location /.well-known/acme-challenge/ {
            root /usr/share/nginx/html;
            try_files $uri =404;
        }

        location / {
            proxy_pass http://culture_aggregator:8002;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_connect_timeout 60s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;
            proxy_buffer_size 4k;
            proxy_buffers 16 8k;
        }
        location /static/ {
            alias /app/ui/static/;
            expires max;
            add_header Cache-Control "public";
        }

        location /media/ {
            alias /usr/src/app/images/;
            expires max;
            add_header Cache-Control "public, max-age=31536000";
            access_log off;
        }
    }
}
